# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-12 16:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LocationCodeMapper',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10)),
                ('building', models.CharField(max_length=100)),
                ('display', models.CharField(max_length=100)),
                ('format', models.CharField(max_length=100)),
                ('note', models.TextField(blank=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, help_text='Set automatically on save.')),
                ('modify_date', models.DateTimeField(auto_now=True, help_text='Set automatically on save.')),
            ],
        ),
    ]
